server:
  port: 9009
spring:
  application:
    name: tensquare-sms

  rabbitmq:
    host: 192.168.184.128
    username: guest
    password: niunan789

aliyun:
  sms:
    accessKeyId: LTAIxo9ZQy1tSHYL
    accessKeySecret: IawJXWPq1Mvg691zCcEOBoyvGvmE5G
    template_code: SMS_94700095
    sign_name: 李腾飞自己做短信测试
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true