server:
  port: 9003
spring:
  application:
    name: tensquare-qa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://58.82.251.33:3306/tensquare_qa?characterEncoding=utf-8
    username: root
    password: niunan789
  jpa:
    database: mysql
    show-sql: true